stages:
  - build

build:
  stage: build
  script:
    - npm install
    - rm -fr /var/www/pintbot.jappinen.fi/*
    - cp -r * /var/www/pintbot.jappinen.fi/
  cache:
    paths:
      - node_modules
    key: "$CI_BUILD_REF"
    untracked: true