stages:
  - deploy

deploy:
  stage: deploy
  script:
    - npm install
    - cp -r * /var/www/pintbot.jappinen.fi/
  cache:
    paths:
      - node_modules
    key: "$CI_BUILD_REF"
    untracked: true